# Generated by Django 3.0.2 on 2020-01-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(blank=True),
        ),
    ]
